name: "Run Script"
on:
  pull_request: # Using pull_request_target instead of pull_request ensures actions use the target branch workflow
    types: [labeled]


jobs:
  find_label_adder:
    runs-on: ubuntu-latest
    environment: terraform
    outputs:
      label-name: ${{ steps.extract_labels.outputs.label-name }}
      user: ${{ steps.extract_labels.outputs.user }}
      pr-opened-by: ${{ steps.extract_labels.outputs.pr-opened-by }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - id: mise
        uses: ./.github/actions/mise

      - name: Use cached mise
        uses: actions/cache@v4
        with:
          path: "${{ steps.mise.outputs.data-dir }}"
          key: ${{ steps.mise.outputs.cache-key }}

      - run: echo $PATH

      - name: Extract label details
        id: extract_labels
        run: |
          echo "---"
          echo "Label added: " ${{ github.event.label.name }}
          echo "Label added by: " ${{ github.event.sender.login }}
          echo "PR opened by: " ${{ github.event.pull_request.user.login }}
          echo "---"
          echo "label-name=${{ github.event.label.name }}" >> "$GITHUB_OUTPUT"
          echo "user=${{ github.event.sender.login }}" >> "$GITHUB_OUTPUT"
          echo "pr-opened-by=${{ github.event.pull_request.user.login }}" >> "$GITHUB_OUTPUT"

      - name: Who added the label?
        run: |
          echo "The label '${{ steps.extract_labels.outputs.label-name }}' was added by ${{ steps.extract_labels.outputs.user }}"

  run-script:
    runs-on: ubuntu-latest
    needs: find_label_adder
    if: needs.find_label_adder.outputs.label-name == 'enhancement' && needs.find_label_adder.outputs.pr-opened-by != needs.find_label_adder.outputs.user
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.1
        with:
          fetch-depth: 0
      - run: ./script.sh


  check-run-remove-label:
    runs-on: ubuntu-latest
    if: github.event.label.name == 'do-something'
    steps:
      - name: Do Something
        run: echo "Doing something"
      - uses: actions-ecosystem/action-remove-labels@v1
        with:
          labels: "do-something"
