name: "Run Script"
on:
  - pull_request_target # Using pull_request_target instead of pull_request ensures actions use the target branch workflow


jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - run: bash ./script.sh
