name: "Run Script"
on:
  pull_request_target: # Using pull_request_target instead of pull_request ensures actions use the target branch workflow
    types: [labeled]


jobs:
  find_label_adder:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Fetch pull request details
        run: |
          PR_DATA=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" "https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}")
          echo "::set-output name=pr_data::${PR_DATA}"

      - name: Extract label details
        id: extract_labels
        run: |
          LABEL_NAME=$(jq -r '.label.name' <<< "${{ github.event }}")
          USER=$(jq -r '.sender.login' <<< "${{ github.event }}")
          echo "::set-output name=label_name::${LABEL_NAME}"
          echo "::set-output name=user::${USER}"

      - name: Who added the label?
        run: |
          echo "The label '${{ steps.extract_labels.outputs.label_name }}' was added by ${{ steps.extract_labels.outputs.user }}"

  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.1
        with:
          fetch-depth: 0
      - run: ./script.sh
